# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 8a08127e1bd7fcf3ebdfb17a392e31b082374a1928b45eb3598fa6c6eb5b2b99bbb4b0a3f4a84f57d45f2236cb7d3a70aa7cc8508ec9425d9b3eb2df56d98c9c

test:
  secret_key_base: e4add6ff046b966a806ab659940b59e786d6b4050593f43cda42b85602fa9f8a72354f68eb30bc256039a8b8050e8603752324a7a8f61e8accada08f71946997

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
